server:
  servlet:
    context-path: /phonebook/api
  port: 8081


spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
#      naming:
#        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
#    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:./data/phonebook

  sql:
    init:
      mode: always
      #    username: "sa"
#    password: ""


